WebApp/Controllers/RedditContextsController.cs
using BlockBase.Dapps.NeverForget.Business.Interfaces;
using BlockBase.Dapps.NeverForget.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlockBase.Dapps.NeverForget.WebApp.Controllers
{
    public class RedditContextsController : Controller
    {
        private readonly ILogger<RedditContextsController> _logger;
        private readonly IRedditContextBusinessObject _redditContextBusinessObject;

        public RedditContextsController(ILogger<RedditContextsController> logger, IRedditContextBusinessObject redditContextBusinessObject)
        {
            _logger = logger;
            _redditContextBusinessObject = redditContextBusinessObject;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var listOp = await _redditContextBusinessObject.GetAllPocoAsync();
            if (!listOp.Success) return Error(listOp.Exception.Message);

            var list = new List<RedditContextViewModel>();
            foreach (var item in listOp.Result)
            {
                list.Add(RedditContextViewModel.FromData(item));
            }


            string logoUrl = Url.Content("~/img/redditRobot.png");
            ViewData["Logo"] = logoUrl;

            return View(list.OrderByDescending(c => c.Date));
        }

        [HttpGet("RedditContexts/Details/{id}")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null) return NotFound();

            var resultOp = await _redditContextBusinessObject.GetPocoAsync((Guid)id);
            if (!resultOp.Success) return Error(resultOp.Exception.Message);

            if (resultOp.Result == null) return NotFound();

            string logoUrl = Url.Content("~/img/redditRobot.png");
            ViewData["Logo"] = logoUrl;

            return View(RedditDetailsViewModel.FromData(resultOp.Result));
        }

        public IActionResult Error(string message)
        {
            _logger.LogError(message);
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return Error(viewModel.Message);
        }
    }
}

WebApp/Controllers/TwitterContextsController.cs
using BlockBase.Dapps.NeverForget.Business.Interfaces;
using BlockBase.Dapps.NeverForget.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlockBase.Dapps.NeverForget.WebApp.Controllers
{
    public class TwitterContextsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ITwitterContextBusinessObject _twitterContextBusinessObject;

        public TwitterContextsController(ILogger<HomeController> logger, ITwitterContextBusinessObject twitterContextBusinessObject)
        {
            _logger = logger;
            _twitterContextBusinessObject = twitterContextBusinessObject;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var twitterContextsList = await _twitterContextBusinessObject.GetAllPocoAsync();
            if (!twitterContextsList.Success) return Error(twitterContextsList.Exception.Message);

            var contextsList = new List<TwitterContextViewModel>();
            foreach (var context in twitterContextsList.Result)
            {
                contextsList.Add(TwitterContextViewModel.FromData(context));
            }

            string logoUrl = Url.Content("~/img/twitterRobot.png");
            ViewData["Logo"] = logoUrl;

            return View(contextsList.OrderByDescending(c => c.Date));
        }

        [HttpGet("TwitterContexts/Details/{contextId}")]
        public async Task<IActionResult> Details(Guid? contextId)
        {
            if (contextId == null) return NotFound();

            var detailedContext = await _twitterContextBusinessObject.GetPocoAsync((Guid)contextId);
            if (!detailedContext.Success) return Error(detailedContext.Exception.Message);

            if (detailedContext.Result == null) return NotFound();

            string logoUrl = Url.Content("~/img/twitterRobot.png");
            ViewData["Logo"] = logoUrl;

            return View(TwitterDetailsViewModel.FromData(detailedContext.Result));
        }

        public IActionResult Error(string message)
        {
            _logger.LogError(message);
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return Error(viewModel.Message);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlockBase.Dapps.NeverForgetBot.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="icon" href="~/img/Logo.png" type="image/gif" sizes="16x16">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
</head>
<body>

    @await Html.PartialAsync("_LogoPartial")

    <header class="sticky-top banner">
        <div>
            <div class="neverForgetHome mx-auto text-center">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <h1>NEVER FORGET BOT</h1>
                </a>
            </div>

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
                <div class="container">
                    <div class="row mx-auto">
                        <button class="navbar-toggler mt-1" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item badge nav-badge m-1">
                                    <input class="nav-link navbar-item" type="button" value="Reddit" onclick="@("window.location.href='" + @Url.Action("Index", "RedditContexts") + "'");" />
                                </li>
                                <li class="nav-item badge nav-badge m-1">
                                    <input class="nav-link navbar-item" type="button" value="Twitter" onclick="@("window.location.href='" + @Url.Action("Index", "TwitterContexts") + "'");" />
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>






    <div class="container mainBody">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="col">
                &copy; 2021 - NeverForgetBot
                <a href="https://www.reddit.com/user/NeverForget-Bot"><i class="icon fab fa-reddit-alien "></i></a>
                <a href="https://twitter.com/_NeverForgetBot"><i class="icon fab fa-twitter"></i></a>
            </div>
        </div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LogoPartial.cshtml
<div class="container logoBackground">
    <div class="row">
        <div class="col center">
            <p class="fixed-top"></p>
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img src="@ViewData["Logo"]" class="logo" />
            </a>
        </div>
    </div>
</div>